# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmrJD8D0p-N98TfUAqr5ge9lokKzAXfs
"""

#~2:50
import requests
from bs4 import BeautifulSoup

url='https://www.toeicswt.co.kr/receipt/examSchList.php'
header_info={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582'}

page=requests.get(url,headers=header_info)
page=page.text

soup=BeautifulSoup(page,'html.parser')

daysing=soup.find_all('tr',class_='ing speaking')
lis1=[]
for item in daysing:
    info=item.text
    info=info.strip()
    lis1.append(info)

days=soup.find_all('tr',class_='speaking')
for item in days:
  info=item.text
  info=info.strip()
  lis1.append(info)

new_item=[]
lis2=[]

for item in lis1:
  new_item=item.split()
  if new_item[-1]=='접수하기':
    lis2.append(new_item)
  elif new_item[-1]=='접수예정':
    lis2.append(new_item)


lis3=[]
for i in range(len(lis2)):
  if lis2[i][1]=='(토)':
    lis3.append(lis2[i])


date=input()
#성적 발표일 2번째 인덱스
#날짜 입력 받아서 그냥 년. 월. 일 비교할까
count=0
year=date[:4]
month=date[4:6]
day=date[6:8]

day_lis=[]
for i in range(len(lis3)):
  opendate=lis3[i][2].split('.')
  day_lis.append(opendate)


okdaylis=[]
for i in range(len(day_lis)):
  if int(year)>int(day_lis[i][0]):
    if day_lis[i] in okdaylis:
        continue
    else:
       okdaylis.append(day_lis[i])
       count+=1


  elif int(year)==int(day_lis[i][0]):
    if int(month)>int(day_lis[i][1]):
      if day_lis[i] in okdaylis:
        continue
      else:
        okdaylis.append(day_lis[i])
        count+=1

    elif int(month)==int(day_lis[i][1]):
      if int(day)>int(day_lis[i][2]):
        if day_lis[i] in okdaylis:
          continue
        else:
          okdaylis.append(day_lis[i])
          count+=1


print(count)